version: '3.1'
services:
    nginx:
        image: nginx:1.20.2
        container_name: nginx_myinvestments
        depends_on:
            - flask_myinvestments
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network_myinvestments
        #ports:
        #    - 80:80
    flask_myinvestments:
        image: myinvestments:latest
        container_name: flask_myinvestments
        networks:
            - network_myinvestments
        ports:
            - 5000:5000
networks:
    network_myinvestments: